### ISSUE TITLE
Setup Kanba board

### ISSUE THREAD

**Issue by sambeck87** [sambeck87/ruby_group_capstone#43]
This project will be done by 3 persons:

Team 1 -> @Juank628 
Team 2 -> @paulsaenzsucre 
Team 3 -> @sambeck87 

https://github.com/sambeck87/ruby_group_capstone/projects/1

**Comment by Munsa1** [comment]
Hi @sambeck87  @Juank628  @paulsaenzsucre , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
N/A

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly add one more card for `Team 1` for the last task which requires the creation of a `schema.sql` file in the screenshot below as it is missing.
![image](https://user-images.githubusercontent.com/81932478/226440013-497c70bd-6db8-4233-8bdf-4e758dcae224.png)

- [ ] Kindly assign points to the group tasks as well as it is a requirement
![image](https://user-images.githubusercontent.com/81932478/226440635-6d25c62b-5b4a-435d-b4ec-8594c6826abe.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by sambeck87** [comment]
- The xpt was added
![Captura desde 2023-03-20 13-30-47](https://user-images.githubusercontent.com/113067895/226446279-e0520e83-2936-4160-a3b1-18f6feb0392c.png)

- The last task was added
![Captura desde 2023-03-20 13-31-04](https://user-images.githubusercontent.com/113067895/226446289-7b4aff4c-0e8f-4e5d-a7df-936a7eb2d785.png)

**Comment by VICTOR-CHUKWU** [comment]
Hi Team, 
# STATUS: APPROVED! 🥇 💯 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
